config/routes.rb
ProjectManagement::Application.routes.draw do

  devise_for :users
  root "home#index"
  get "/" => "home#index"
  get "/about" => "home#about"
  get "/questions" => "questions#new"

  resources :projects do
    resources :tasks do
      member do
        get :status
      end
    end
    resources :discussions
  end

  resources :discussions, only: [] do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates_presence_of :body
  belongs_to :discussion
  belongs_to :user
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	validates :title, :description, presence: true
  belongs_to :project
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, through: :discussions, dependent: :destroy
  belongs_to :user


	validates :title, presence: true, uniqueness: true

	default_scope order("created_at DESC")

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

	validates :title, presence: true, uniqueness: true
  scope :ordered_by_creation, -> { order("status DESC, created_at DESC")}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :tasks
  has_many :projects
  has_many :discussions


  validates :first_name, :last_name, presence: true

  def full_name
    if first_name || last_name
      "#{first_name.capitalize} #{last_name.capitalize}".squeeze(" ").strip
    else
      email
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  before_action :configure_devise_params, if: :devise_controller?

  private

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!


  def create
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.new(comment_attributes)
    @comment.user = current_user
    if @comment.save
      redirect_to [@discussion.project, @discussion], notice: "comments submmited"
    else
      render :new, alert: "error occurred"
    end
  end


  def new
    @discussion = Discussion.find(params[:discussion_id])
    @comment = Comment.new
    
  end

  def destroy
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.find(params[:id])
    if @comment.destroy
      redirect_to [@discussion.project, @discussion], alert: "comment deleted!"
    end
  end


  private

  def comment_attributes
    params.require(:comment).permit([:body])
  end


end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_discussion, only: [:show, :edit, :destroy, :update]


  def index
  end

  def create
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.new(discussion_attributes)
    @discussion.user = current_user
    if @discussion.save
      redirect_to @project, notice: "Discussion Created Succefully!"
    else
      render :new, alert: "Something was wrong, please try again."
    end
  end

  def new
    @project = Project.find params[:project_id]
    @discussion = Discussion.new
  end

  def update
  end

  def edit
  end

  def show
  end

  def destroy
    if @discussion.destroy
      redirect_to @project, notice: "Discussion Deleted!"
    else
      redirect_to @project, alert: "Some error occured, please contact admin!"
    end
  end


  private

  def discussion_attributes
    params.require(:discussion).permit([:title, :description])
  end

  def find_discussion
    @project = Project.find(params[:project_id])
    @discussion = @project.discussions.find(params[:id])
  end   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	before_action :find_project, only: [:edit, :destroy, :update]

	def index
		@projects = Project.all
	end

	def create
		@project = Project.new(project_attributes)
		@project.user = current_user

		if @project.save
			# flash[:notice] = "Your question was created successfully!"
			redirect_to projects_path, notice: "Your project was created successfully!"
		else
			render :new, alert: "We are sorry, your project was not created. Please try again."
		end

	end

	def new
		@project = Project.new
	end

	def edit
	end

	def show
		@project = Project.find(params[:id])
		@task = Task.new
		@tasks = @project.tasks.ordered_by_creation
		@discussions = @project.discussions
	end

	def update
		if @project.update_attributes(project_attributes)
			redirect_to @project, notice: "Your project was updated!"
		else
			render :edit, alert: "Error Occured."
		end
	end

	def destroy
		if @project.destroy
			redirect_to projects_path, notice: "Your project was deleted!"
		else
			redirect_to projects_path, 
			alert: "We are sorry, an error has occured while deleting your project! Please try again later."
		end
	end


	private

	def project_attributes
		params.require(:project).permit([:title])
	end



	def find_project
		# @project = Project.find(params[:id])

		@project = current_user.projects.find_by_id(params[:id])
		redirect_to root_path, alert: "Access Denied" unless @project
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController



	def new
		@question = Question.new
	end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_tasks, only: [:edit, :destroy, :update, :status]
  
  def create
    @project = current_user.projects.find_by_id(params[:project_id])
    # @project = Project.find params[:project_id]
    if @project
      @task = @project.tasks.new(task_attributes)
      @task.user = current_user
      if @task.save
        redirect_to @project, notice: "Task Created Succefully!"
      else
        @tasks = @project.tasks.ordered_by_creation
        @discussions = @project.discussions
        render '/projects/show', alert: "Task was not created!"
      end
    else
      redirect_to root_path, alert: "Access Denied" unless @project
    end

  end

  def status   
    if @task.status == "Not Done"
      @task.status = "Done"
    else
      @task.status = "Not Done"
    end
    @task.save
    redirect_to @project
  end

	def index
	end

	def new
	end

	def edit
    
	end

	def show
    @project = Project.find params[:project_id]
    @task = @project.tasks.find(params[:id])
	end

	def update  
    if @task.update_attributes(task_attributes)
      redirect_to @project, notice: "Question updated successfully!"
    else
      render :edit, alert: "Couldn't Update!"
    end
	end

	def destroy
    
    if @task.destroy
      redirect_to @project, notice: "Task Deleted Succefully!"
    else
      redirect_to @project, alert: "We are sorry, there was an error in deleting your Task!"
    end
	end

	private

  def task_attributes
    params.require(:task).permit([:title, :body])
  end	


  def find_tasks
    # @project = Project.find params[:project_id]
    # @task = @project.tasks.find(params[:id])

    @project = current_user.projects.find_by_id(params[:project_id])
    if @project
      @task = @project.tasks.find(params[:id])
    else
      redirect_to root_path, alert: "Access Denied"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

		def formatted_date(date)
			date.strftime("%Y-%b-%d")
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/new.html.erb
<div class="space"></div>
<h1>Add A Comment</h1>
<%= form_for @comment, url: discussion_comments_path(@discussion) do |f| %>

  <%= f.label :body, "Enter your comment" %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit" %>


<% end %>

app/views/discussions/index.html.erb
index.html.erb

app/views/discussions/new.html.erb
<% if @discussion.errors.any? %>
  <ul>
    <% @discussion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h1>New Discussion</h1>
<div class="space"></div>

<%= form_for @discussion, url: project_discussions_path(@project) do |f| %>

  <%= f.label :title, "Topic:" %>  
  <%= f.text_field :title %>
  <br>
  <%= f.text_area :description %>
  <br>

  <%= f.submit "Create Discussion", class: "btn btn-secondary" %>


<% end %>

app/views/discussions/show.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <h1><%= @discussion.title %></h1>
      <p><%= @discussion.description %></p>
      <%= button_to "Add Comment!", new_discussion_comment_path(@discussion), method: :get, class: "btn btn-default" %>
    </div>
  </div>
  <% @discussion.comments.each do |comment| %>
    <div class="row">
      <div class="well">
       <p><%= comment.body %></p>
        <%= button_to "Delete", discussion_comment_path(@discussion, comment), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/about.html.erb
<h1> This is the about page header </h1>

<p>This is the about page!</p>
<%= link_to "Click Me", "javascript:void(0);", class: "button1 btn btn-primary" %>
<%= link_to "Enlarge Me", "javascript:void(0);", class: "button2 btn btn-primary" %>
<br>
<br>
<%= text_field_tag "box", nil, class: "box", placeholder: "Enter something here..." %>
<br>
<span class="boxResult"></span>
<br>
<%= text_field_tag "color-box", nil, class: "color-box", placeholder: "Enter some color here..." %>
<br>
<span class="boxColor"></span>
<h3>Picture:</h3>
<p><img src="http://www.designbolts.com/wp-content/uploads/2013/06/despicable-me-characters-wallpaper.jpg" width="200" height="250"></img></p>
<p id="test"></p>
<h3>Name:</h3>
<p>Alex Kuang</p>
<br>
<h3>Email:</h3>
<p>uoroaix@gmail.com</p>
<br>
<h3>Phone:</h3>
<p>1234567894</p>
<br>
<h3>List:</h3>
<ul>
  <li>vancouver</li>
  <li>richmond</li>
  <li>burnaby</li>
</ul>

app/views/home/index.html.erb
<h1> This is the homepage header </h1>

<p>Welcome to Project Management's Homepage!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagement</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="space"></div>
<div class="container-fluid">


	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">

					&nbsp;
						<%= link_to "Home", root_path, class: "btn btn-default"  %>
				  &nbsp;
						<%= link_to "About", about_path, class: "btn btn-default" %>
          &nbsp;
						<%= link_to "Projects", projects_path, class: "btn btn-default" %>
          &nbsp;
            <%= link_to "New Project", new_project_path, class: "btn btn-default" %>          

            
            <div class="pull-right">
              <% if user_signed_in? %>
                <div style="color:white;font-size:20px">Hello <%= current_user.full_name %></div>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
              <% else %>
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-default" %>
              <% end %>
            </div>

      </div>
	</div>


<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/projects/_discussions.html.erb
<h1>Discussions</h1>
<hr>
<div class="space"></div>
<% @discussions.each do |discussion| %>
<div class="well">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2><%= link_to discussion.title, project_discussion_path(@project, discussion) %></h2>
        <p><%= discussion.description %></p>
      </div>
      <div class="col-md-3">
      <%= button_to "Delete", project_discussion_path(@project, discussion), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete?"} %>
      <br>
      <%= button_to "Edit", edit_project_discussion_path(@project, discussion), method: :get, class: "btn btn-default" %>
      <br>
      <p>Created On: <%= formatted_date(discussion.created_at) %></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
	<ul>
		<% @project.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @project do |f| %>

	<%= f.label :title, "Enter your project's title:" %>  
	<%= f.text_field :title %>
	<br>

  <%= f.submit button_label, class: "btn btn-secondary" %>


<% end %>

app/views/projects/_tasks.html.erb
<h1>Tasks</h1>
<hr>
<%= form_for @task, url: project_tasks_path(@project) do |f| %>
  <%= f.label :title, "Your Task's Title: " %>
  <%= f.text_field :title %>
  <br>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "New Task!", class: "btn btn-default" %>
<% end %> 
<div class="space"></div>
<% @tasks.each do |task| %>
<div class="well">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2><%= task.title %></h2>
        <p><%= task.body %></p>
      </div>
      <div class="col-md-3">
      <%= button_to task.status, status_project_task_path(@project, task), method: :get, class: "btn btn-default" %>
      <br>
      <%= button_to "Delete", project_task_path(@project, task), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete?"} %>
      <br>
      <%= button_to "Edit", edit_project_task_path(@project, task), method: :get, class: "btn btn-default" %>
      <br>
      <p>Created On: <%= formatted_date(task.created_at) %></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1> Edit Your Project Title Here </h1>

<%= render "form", button_label: "Save~!" %>

app/views/projects/index.html.erb
<h1> Your Projects ! </h1>

<% @projects.each do |project| %>
<div class="jumbotron">
	<h2><%= link_to project.title, project %></h2>
	<p>Created On: <%= formatted_date(project.created_at) %></p>
  <p>Created By: <%= project.user.full_name %></p>
</div>


<% end %>

app/views/projects/new.html.erb
<h1> Create Your Own Project! </h1>


<%= render "form", button_label: "Submit!" %>

app/views/projects/show.html.erb
  <div class="row">
    <div class="col-md-6">
      <h1>Project title: <%= @project.title %></h1>
    </div>
    <div class="col-md-6">
    <br>
      <%= button_to "Edit Project Title", edit_project_path(@project), method: :get, class: "btn btn-default" %>
    <br>
      <%= button_to "Add A Discussion", new_project_discussion_path(@project), method: :get, class: "btn btn-default" %>
    <br>
      <%= button_to "Delete Project!", project_path(@project), method: :delete,
      data: {confirm: "Are you sure you want to delete this project?"}, class: "btn btn-danger" %>
    <br>

    </div>
  </div>

<div class="space"></div>
<hr>
<div class="row">
  <div class="col-md-6">
  <%= render "/projects/tasks" %>
  </div>
  <div class="col-md-6">
  <%= render "/projects/discussions" %>
  </div>
</div>

app/views/questions/new.html.erb
<h1> Give me a new question</h1>

<%= form_for @question do |f| %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control" %>
	</div>
	<%= f.submit "Save", class: "btn btn-warning" %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks</h1>
<hr>
<%= form_for @task, url: project_task_path(@project, @task) do |f| %>
  <%= f.label :title, "Your Task's Title: " %>
  <%= f.text_field :title %>
  <br>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Save!", class: "btn btn-default" %>
<% end %> 